INSERT INTO plant_nodes (
    plantNodeUUID,
    nodeName,
    connectedUserUUID,
    plantSpecies,
    wateringFrequencyID,
    lightThresholdID,
    humidityThresholdID,
    moistureThresholdID,
    temperatureThresholdID,
    soilMoisture,
    lastWatered,
    location,
    needsWatering,
    healthStatus
) VALUES (
    UUID(),
    'Node A1',
    'usr-1234abcd-5678-efgh-ijkl-9012mnopqrst',
    'Ficus Elastica',
    1,
    2,
    3,
    4,
    5,
    35.5,
    NOW(),
    'Greenhouse Section B',
    FALSE,
    'Healthy'
);
