INSERT INTO plant_nodes (
    nodeName,
    connectedUserUUID,
    plantSpecies,
    wateringFrequencyID,
    lightThresholdID,      
    humidityThresholdID,   
    moistureThresholdID,   
    temperatureThresholdID,  -- Add this line
    soilMoisture,
    lastWatered,
    location,
    temperature,
    humidity,
    lightLevel,
    healthStatus,
    batteryLevel,
    isOnline,
    lastSync,
    nextWateringTime,
    macAddress
) VALUES (
    'Plant-Node-0001',
    'usr-uuid-goes-here',
    'Monstera Deliciosa',
    1,
    3,                     
    4,                     
    4,
    2,                     -- Add value (2 for 'Moderate' temperature)
    75.5,
    CURRENT_TIMESTAMP,
    'Living Room Window',
    23.5,
    65.0,
    800.0,
    'Healthy',
    98.5,
    TRUE,
    CURRENT_TIMESTAMP,
    DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 24 HOUR),
    '58:BF:25:DC:12:E3'
);