CREATE TABLE `plant_nodes` (
  `plantNodeUUID` char(39) NOT NULL,
  `nodeName` varchar(100) NOT NULL,
  `connectedUserUUID` char(36) DEFAULT NULL,
  `plantSpecies` varchar(100) DEFAULT NULL,
  `wateringFrequencyID` int NOT NULL,
  `lightThresholdID` int NOT NULL,
  `humidityThresholdID` int NOT NULL,
  `moistureThresholdID` int NOT NULL,
  `temperatureThresholdID` int NOT NULL,
  `soilMoisture` float NOT NULL,
  `lastWatered` timestamp NOT NULL,
  `location` varchar(100) DEFAULT NULL,
  `needsWatering` tinyint(1) DEFAULT ''0'',
  `lastInitialWaterTrigger` timestamp NULL DEFAULT NULL,
  `maxWateringTime` int DEFAULT ''30'',
  `temperature` float DEFAULT NULL,
  `humidity` float DEFAULT NULL,
  `lightLevel` float DEFAULT NULL,
  `healthStatus` varchar(20) DEFAULT ''Healthy'',
  `batteryLevel` float DEFAULT NULL,
  `isOnline` tinyint(1) DEFAULT ''1'',
  `lastSync` timestamp NULL DEFAULT NULL,
  `nextWateringTime` timestamp NULL DEFAULT NULL,
  `lastMaintenance` timestamp NULL DEFAULT NULL,
  `notes` text,
  `macAddress` char(17) NOT NULL,
  `createdAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`plantNodeUUID`),
  UNIQUE KEY `nodeName` (`nodeName`),
  UNIQUE KEY `connectedUserUUID` (`connectedUserUUID`),
  KEY `lightThresholdID` (`lightThresholdID`),
  KEY `humidityThresholdID` (`humidityThresholdID`),
  KEY `moistureThresholdID` (`moistureThresholdID`),
  KEY `temperatureThresholdID` (`temperatureThresholdID`),
  KEY `plant_nodes_ibfk_1` (`wateringFrequencyID`),
  CONSTRAINT `plant_nodes_ibfk_1` FOREIGN KEY (`wateringFrequencyID`) REFERENCES `watering_frequencies` (`wateringFrequencyID`),
  CONSTRAINT `plant_nodes_ibfk_2` FOREIGN KEY (`lightThresholdID`) REFERENCES `threshold-light-sensitivity` (`lightThresholdID`),
  CONSTRAINT `plant_nodes_ibfk_3` FOREIGN KEY (`humidityThresholdID`) REFERENCES `threshold-humidity` (`humidityThresholdID`),
  CONSTRAINT `plant_nodes_ibfk_4` FOREIGN KEY (`moistureThresholdID`) REFERENCES `threshold-soil-moisture` (`moistureThresholdID`),
  CONSTRAINT `plant_nodes_ibfk_5` FOREIGN KEY (`temperatureThresholdID`) REFERENCES `threshold-temperature` (`temperatureThresholdID`),
  CONSTRAINT `valid_mac` CHECK (regexp_like(`macAddress`,_utf8mb4''^[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5}$'')),
  CONSTRAINT `valid_moisture` CHECK (((`soilMoisture` >= 0) and (`soilMoisture` <= 100)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



